-- Generated by hyprconf2lua v1.3.2
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- https://wiki.hyprland.org/Configuring/Configuring-Hyprland/

hl.monitor({
    output   = "DP-2",
    mode     = "2560x1440@60",
    position = "1080x0",
    scale    = 1,
})

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "1920x1080@60",
    position = "0x0",
    scale    = 1,
    transform = 1,
})

-- ==--==--==--==--==--==--==--==--==--==--==--== #

hl.workspace_rule({
    workspace = 1,
    persistent = true,
    monitor = "DP-2",
})

hl.workspace_rule({
    workspace = 2,
    persistent = true,
    monitor = "DP-2",
})

hl.workspace_rule({
    workspace = 3,
    persistent = true,
    monitor = "DP-2",
})

hl.workspace_rule({
    workspace = 4,
    persistent = true,
    monitor = "DP-2",
})

hl.workspace_rule({
    workspace = 5,
    persistent = true,
    monitor = "DP-2",
})

hl.workspace_rule({
    workspace = 6,
    persistent = true,
    monitor = "DP-2",
})

hl.workspace_rule({
    workspace = 7,
    persistent = true,
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = 8,
    persistent = true,
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = 9,
    persistent = true,
    monitor = "HDMI-A-1",
})

require("configs.environ")
require("configs.exec")
require("configs.binds")
require("configs.settings")
require("configs.animations")
require("configs.rules")
require("dms.cursor")
