-- Generated by hyprconf2lua v1.3.2
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ▄▄▄▄· ▪   ▐ ▄ ·▄▄▄▄  .▄▄ · 

-- ▐█ ▀█▪██ •█▌▐███▪ ██ ▐█ ▀. 

-- ▐█▀▀█▄▐█·▐█▐▐▌▐█· ▐█▌▄▀▀▀█▄

-- ██▄▪▐█▐█▌██▐█▌██. ██ ▐█▄▪▐█

-- ·▀▀▀▀ ▀▀▀▀▀ █▪▀▀▀▀▀•  ▀▀▀▀ 

-- https://wiki.hyprland.org/Configuring/Binds/

local HYPR_SCRIPTS = "~/.config/hypr/scripts"

local ROFI_MENUS = "~/.config/rofi/bin"

local SCRIPTS = "~/.local/bin"

-- Tiny wrapper script to add toggle behavior to all menus using rofi

local TOGGLE_ROFI = "~/.local/bin/toggle_rofi"

-- Reload hyprland config

hl.bind("SUPER + CTRL" .. " + " .. "R", hl.dsp.exec_cmd("hyprctl reload"))

-- ==--==--==--==--==--==--==--==--==--==--==--== #

hl.bind("SUPER" .. " + " .. "C", hl.dsp.window.close())

hl.bind("SUPER + SHIFT" .. " + " .. "C", hl.dsp.window.kill())

hl.bind("SUPER" .. " + " .. "RETURN", hl.dsp.exec_cmd("alacritty"))

hl.bind("SUPER + SHIFT" .. " + " .. "RETURN", hl.dsp.exec_cmd("[float] alacritty"))

-- ==--==--==--==--==--==--==--==--==--==--==--== #

hl.bind("SUPER" .. " + " .. "X", hl.dsp.exec_cmd("dms ipc call lock lock"))

hl.bind("SUPER" .. " + " .. "D", hl.dsp.exec_cmd("~/.config/rofi/bin/drun"))

hl.bind("SUPER + SHIFT" .. " + " .. "F", hl.dsp.exec_cmd("firefox"))

hl.bind("SUPER + SHIFT" .. " + " .. "N", hl.dsp.exec_cmd("nautilus"))

hl.bind("SUPER + SHIFT" .. " + " .. "V", hl.dsp.exec_cmd("pavucontrol"))

hl.bind("SUPER + SHIFT" .. " + " .. "P", hl.dsp.exec_cmd("dms ipc call bar toggle name Main Bar"))

hl.bind("SUPER + SHIFT" .. " + " .. "T", hl.dsp.exec_cmd("Telegram"))

--Window manipulations ==--==--==--==--==--==--==--==--==--==--==--== #

hl.bind("SUPER" .. " + " .. "tab", hl.dsp.focus({ workspace = "previous" }))

hl.bind("SUPER" .. " + " .. "W", hl.dsp.window.center())

hl.bind("SUPER" .. " + " .. "U", hl.dsp.window.pin())

hl.bind("SUPER" .. " + " .. "T", hl.dsp.window.pseudo())

hl.bind("SUPER" .. " + " .. "SPACE", hl.dsp.exec_cmd("hyprctl --batch dispatch togglefloating ; dispatch centerwindow 1"))

-- Resize window

hl.bind("SUPER + CTRL + right", hl.dsp.window.resize({ x = 70, y = 0, relative = true }))
hl.bind("SUPER + CTRL + left", hl.dsp.window.resize({ x = -70, y = 0, relative = true }))
hl.bind("SUPER + CTRL + up", hl.dsp.window.resize({ x = 0, y = -70, relative = true }))
hl.bind("SUPER + CTRL + down", hl.dsp.window.resize({ x = 0, y = 70, relative = true }))

-- Floating / Fullscreen

-- bind = SUPER SHIFT, F, exec, hyprctl --batch "dispatch togglefloating ; dispatch centerwindow 1"

hl.bind("SUPER" .. " + " .. "F", hl.dsp.window.fullscreen())

-- dwindle only

hl.bind("SUPER" .. " + " .. "A", hl.dsp.layout("swapsplit"))

hl.bind("SUPER" .. " + " .. "Z", hl.dsp.layout("togglesplit"))

--Waybar ==--==--==--==--==--==--==--==--==--==--==--== #

hl.bind("SUPER" .. " + " .. "P", hl.dsp.exec_cmd("pkill -SIGUSR1 waybar"))

-- show-hide waybar on space

hl.bind("SUPER + CTRL" .. " + " .. "P", hl.dsp.exec_cmd("~/.local/bin/restart_waybar"))

-- restart waybar

-- master only

hl.bind("SUPER" .. " + " .. "A", hl.dsp.layout("rollprev"))

hl.bind("SUPER" .. " + " .. "X", hl.dsp.layout("swapwithmaster master"))

hl.bind("SUPER" .. " + " .. "D", hl.dsp.layout("rollnext"))

hl.bind("SUPER + SHIFT" .. " + " .. "A", hl.dsp.layout("cycleprev"))

hl.bind("SUPER + SHIFT" .. " + " .. "X", hl.dsp.layout("focusmaster"))

hl.bind("SUPER + SHIFT" .. " + " .. "D", hl.dsp.layout("cyclenext"))

-- A bunch of rofi menus

--bind = SUPER,       R, exec, $TOGGLE_ROFI $ROFI_MENUS/drun

--bind = SUPER SHIFT, R, exec, $TOGGLE_ROFI $ROFI_MENUS/run

--bind = SUPER,       V, exec, $TOGGLE_ROFI $ROFI_MENUS/clipboard 

--bind = SUPER,       E, exec, $TOGGLE_ROFI $ROFI_MENUS/filebrowser

--bind = SUPER,  ESCAPE, exec, $TOGGLE_ROFI $ROFI_MENUS/logout

-- Show bookmars menu

hl.bind("SUPER + SHIFT" .. " + " .. "E", hl.dsp.exec_cmd("~/.local/bin/toggle_rofi ~/.local/bin/bookmarks"))

-- Wallpapers select menu

hl.bind("SUPER" .. " + " .. "Y", hl.dsp.exec_cmd("~/.local/bin/toggle_rofi python3 ~/.local/bin/auto_walls/rofi_selector.py"))

--### WORK IN PROGRESS ####

--### bind = SUPER SHIFT, Y, exec, python3 $BIG_SCRIPTS/themxr/themxr.py

--Misc ==--==--==--==--==--==--==--==--==--==--==--== #

-- Decrease volume / gaps-in / gaps-out

hl.bind("SUPER" .. " + " .. "MINUS", hl.dsp.exec_cmd("~/.local/bin/change_volume -2"))

hl.bind("SUPER" .. " + " .. "EQUAL", hl.dsp.exec_cmd("~/.local/bin/change_volume +2"))

hl.bind("SUPER + SHIFT" .. " + " .. "MINUS", hl.dsp.exec_cmd("~/.config/hypr/scripts/resize_gaps in -2"))

hl.bind("SUPER + CTRL" .. " + " .. "MINUS", hl.dsp.exec_cmd("~/.config/hypr/scripts/resize_gaps out -2"))

hl.bind("SUPER + SHIFT" .. " + " .. "EQUAL", hl.dsp.exec_cmd("~/.config/hypr/scripts/resize_gaps in 2"))

hl.bind("SUPER + CTRL" .. " + " .. "EQUAL", hl.dsp.exec_cmd("~/.config/hypr/scripts/resize_gaps out 2"))

hl.bind("SUPER" .. " + " .. "period", hl.dsp.exec_cmd("playerctl next"))

-- next track with main mod + .

hl.bind("SUPER" .. " + " .. "comma", hl.dsp.exec_cmd("playerctl previous"))

-- prev track with main mod + ,

hl.bind("SUPER" .. " + " .. "slash", hl.dsp.exec_cmd("playerctl play-pause"))

-- play / pause on mod + slash

hl.bind("SUPER + SHIFT" .. " + " .. "slash", hl.dsp.exec_cmd("python3 ~/.local/bin/auto_walls/toggle_timer.py"))

-- Next / Prev wallpaper

--bind = SUPER SHIFT, period, exec, python3 $SCRIPTS/auto_walls/set_next.py

--bind = SUPER SHIFT, comma, exec,  python3 $SCRIPTS/auto_walls/set_prev.py

hl.bind("SUPER" .. " + " .. "W", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/change_wallpaper.sh"))

-- Set floating workspace

-- Screenshot / video_recording

hl.bind("Print", hl.dsp.exec_cmd("flameshot gui"))

hl.bind("SHIFT" .. " + " .. "Print", hl.dsp.exec_cmd("~/.local/bin/screenshot --select"))

hl.bind("CTRL" .. " + " .. "Print", hl.dsp.exec_cmd("~/.local/bin/toggle_recording"))

hl.bind("CTRL + SHIFT" .. " + " .. "Print", hl.dsp.exec_cmd("~/.local/bin/toggle_recording --select"))

-- Tag window

hl.bind("SUPER + 0", hl.dsp.window.tag({ tag = "+bordered" }))
hl.bind("SUPER + 9", hl.dsp.window.tag({ tag = "+opaque" }))

-- Move focus win + arrow keys

hl.bind("SUPER" .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind("SUPER" .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind("SUPER" .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind("SUPER" .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

-- Swap window 

hl.bind("SUPER + SHIFT" .. " + " .. "left", hl.dsp.window.swap({ direction = "left" }))

hl.bind("SUPER + SHIFT" .. " + " .. "right", hl.dsp.window.swap({ direction = "right" }))

hl.bind("SUPER + SHIFT" .. " + " .. "up", hl.dsp.window.swap({ direction = "up" }))

hl.bind("SUPER + SHIFT" .. " + " .. "down", hl.dsp.window.swap({ direction = "down" }))

-- Move windows

hl.bind("SUPER + CTRL + SHIFT" .. " + " .. "left", { direction = "l" })

hl.bind("SUPER + CTRL + SHIFT" .. " + " .. "right", { direction = "r" })

hl.bind("SUPER + CTRL + SHIFT" .. " + " .. "up", { direction = "u" })

hl.bind("SUPER + CTRL + SHIFT" .. " + " .. "down", { direction = "d" })

-- Workspaces [1-6] 

hl.bind("SUPER" .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind("SUPER" .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind("SUPER" .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind("SUPER" .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind("SUPER" .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind("SUPER" .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind("SUPER" .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

-- Moving windows to workspace [1-6]

hl.bind("SUPER + SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }, { follow = false }))

hl.bind("SUPER + SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }, { follow = false }))

hl.bind("SUPER + SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }, { follow = false }))

hl.bind("SUPER + SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }, { follow = false }))

hl.bind("SUPER + SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }, { follow = false }))

hl.bind("SUPER + SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }, { follow = false }))

hl.bind("SUPER + SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }, { follow = false }))

-- Moving windows to workspace and move to workspace [1-6]

hl.bind("SUPER + CTRL" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind("SUPER + CTRL" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind("SUPER + CTRL" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind("SUPER + CTRL" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind("SUPER + CTRL" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind("SUPER + CTRL" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind("SUPER + CTRL" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

-- Special workspace

hl.bind("SUPER" .. " + " .. "S", hl.dsp.workspace.toggle_special("magic"))

hl.bind("SUPER + SHIFT" .. " + " .. "S", hl.dsp.window.move({ workspace = "special:magic" }, { follow = false }))

hl.bind("SUPER + SHIFT + CTRL" .. " + " .. "S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Binds for low signals

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("~/.local/bin/change_volume -5"))

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("~/.local/bin/change_volume +5"))

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"))

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("pactl set-sink-mute @DEFAULT_SINK@ toggle"))

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("~/.local/bin/toggle_microphone"))

hl.bind("XF86AudioPlayPause", hl.dsp.exec_cmd("playerctl play-pause"))

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play"))

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl pause"))

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("~/.local/bin/brightness 4%+"))

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("~/.local/bin/brightness 4%-"))

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"))

hl.bind("XF86KbdBrightnessDown", hl.dsp.exec_cmd("asusctl -p"))

hl.bind("XF86KbdBrightnessUp", hl.dsp.exec_cmd("asusctl -n"))

hl.bind("XF86Launch1", hl.dsp.exec_cmd("~/.local/bin/cycle_profile"))

hl.bind("XF86Launch4", hl.dsp.exec_cmd("rog-control-center"))

hl.bind("XF86Calculator", hl.dsp.exec_cmd("qalculate-gtk"))

hl.bind("Pause", hl.dsp.exec_cmd("playerctl pause"))

-- Mouse binds

hl.bind("SUPER" .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind("SUPER" .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })
