-- Generated by hyprconf2lua v1.3.2
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ▄▄▄ . ▐ ▄  ▌ ▐·

-- ▀▄.▀·•█▌▐█▪█·█▌

-- ▐▀▀▪▄▐█▐▐▌▐█▐█•

-- ▐█▄▄▌██▐█▌ ███ 

--  ▀▀▀ ▀▀ █▪. ▀  

-- https://wiki.hyprland.org/Configuring/Environment-variables/

-- GPU used for hyprland 

-- For some reason, by default hyprland uses both dedicated & integrated card

-- which can lead to power management problems, because dedicated gpu won't turn off *

hl.env("AQ_DRM_DEVICES", "/dev/dri/card1:/dev/dri/card0")

-- *Figured it out. discrete gpu wont turn off because it is still needed for hdmi port (at least on my laptop)

-- Also, being used with this variable, it actually consumes same power as if it would not be specified

-- Disables realtime priority setting by Hyprland. I Allready have ananicy

hl.env("HYPRLAND_NO_RT", 1)

-- Disable gpu buffer sync?? no clue what it does. 

-- Im testing it and waiting documentation from aquamarine :)

-- env = AQ_MGPU_NO_EXPLICIT, 1

-- Wayland realted variables

hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")

hl.env("DESKTOP_SESSION", "Hyprland")

hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")

hl.env("XDG_SESSION_TYPE", "wayland")

-- Setting nvidia as opengl provider

-- env = __GLX_VENDOR_LIBRARY_NAME, nvidia

-- env = VKD3D_FILTER_DEVICE_NAME, NVIDIA

-- env = VK_ICD_FILENAMES, /usr/share/vulkan/icd.d/nvidia_icd.json

-- GTK4 apps use discrete gpu, this fixes it

-- I've put the same into /etc/environment 

hl.env("GSK_RENDERER", "opengl")

-- Cache related variables

hl.env("__GL_SHADER_DISK_CACHE", 1)

hl.env("__GL_SHADER_DISK_CACHE_SKIP_CLEANUP", 1)

-- Qt environment variables

hl.env("QT_QPA_PLATFORM", "wayland")

hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", 1)

-- Global XDG environment variables 

hl.env("XDG_STATE_HOME", "local_var_HOME/.local/state")

hl.env("XDG_DATA_HOME", "local_var_HOME/.local/share")

hl.env("XDG_CONFIG_HOME", "local_var_HOME/.config")

hl.env("XDG_CACHE_HOME", "local_var_HOME/.cache")

hl.env("XDG_DESKTOP_DIR", "local_var_HOME/workspace")

hl.env("XDG_DOWNLOAD_DIR", "local_var_HOME/downloads")

hl.env("XDG_TEMPLATES_DIR", "local_var_HOME/.local/share/templates")

hl.env("XDG_PUBLICSHARE_DIR", "local_var_HOME/")

hl.env("XDG_DOCUMENTS_DIR", "local_var_HOME/docs")

hl.env("XDG_MUSIC_DIR", "local_var_HOME/media/music")

hl.env("XDG_PICTURES_DIR", "local_var_HOME/media/pictures")

hl.env("XDG_VIDEOS_DIR", "local_var_HOME/media/videos")

hl.env("XDG_GAMES_DIR", "local_var_HOME/media/games")

-- Misc

hl.env("__GL_SHADER_DISK_CACHE_PATH", "local_var_HOME/.cache/nv")

hl.env("CUDA_CACHE_PATH", "local_var_HOME/.cache/cuda")

hl.env("GNUPGHOME", "local_var_HOME/.local/share/gnupg")

hl.env("SCRIPTS", "local_var_HOME/.local/bin")
