-- Generated by hyprconf2lua v1.3.2
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ▄▄▄ .▐▄• ▄ ▄▄▄ . ▄▄· 

-- ▀▄.▀· █▌█▌▪▀▄.▀·▐█ ▌▪

-- ▐▀▀▪▄ ·██· ▐▀▀▪▄██ ▄▄

-- ▐█▄▄▌▪▐█·█▌▐█▄▄▌▐███▌

--  ▀▀▀ •▀▀ ▀▀ ▀▀▀ ·▀▀▀ 


-- exec-once = waybar










-- Clipboard





-- Startup scripts



-- Wallpapers daemon

--exec-once = python3 ~/scripts/big/auto_walls/auto_walls.py

--exec-once = ~/.local/bin/connect_to_last_device

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("swww-daemon")
    hl.exec_cmd("dms run")
    hl.exec_cmd("hyprctl setcursor Bibata-Modern-Ice 24")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface cursor-theme Bibata-Modern-Ice")
    hl.exec_cmd("gammastep-indicator")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("/usr/lib/xfce-polkit/xfce-polkit")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("swaync")
    hl.exec_cmd("flameshot")
    hl.exec_cmd("wl-paste --type text --watch cliphist -max-items=15 store")
    hl.exec_cmd("wl-paste --type image --watch cliphist -max-items=5 store")
    hl.exec_cmd("wl-clip-persist --clipboard regular")
    hl.exec_cmd("brightnessctl -s -d asus::kbd_backlight")
    hl.exec_cmd("~/.local/bin/hook/startup/ensure_power_profile.sh")
    hl.exec_cmd("waypaper")
end)
