-- Generated by hyprconf2lua v1.3.2
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ▄▄▌ ▐ ▄▌▪   ▐ ▄ ·▄▄▄▄  ▄▄▌ ▐ ▄▌    ▄▄▄  ▄• ▄▌▄▄▌  ▄▄▄ ..▄▄ · 

-- ██· █▌▐███ •█▌▐███▪ ██ ██· █▌▐█    ▀▄ █·█▪██▌██•  ▀▄.▀·▐█ ▀. 

-- ██▪▐█▐▐▌▐█·▐█▐▐▌▐█· ▐█▌██▪▐█▐▐▌    ▐▀▀▄ █▌▐█▌██▪  ▐▀▀▪▄▄▀▀▀█▄

-- ▐█▌██▐█▌▐█▌██▐█▌██. ██ ▐█▌██▐█▌    ▐█•█▌▐█▄█▌▐█▌▐▌▐█▄▄▌▐█▄▪▐█

--  ▀▀▀▀ ▀▪▀▀▀▀▀ █▪▀▀▀▀▀•  ▀▀▀▀ ▀▪    .▀  ▀ ▀▀▀ .▀▀▀  ▀▀▀  ▀▀▀▀ 

-- https://wiki.hyprland.org/Configuring/Window-Rules/

-- Bookmarks window in zen browser

hl.window_rule({
    name  = "windowrule-1",
    match = {
        title = "Library",
        class = "zen-browser",
    },
    float = true,
})

-- Thunar

hl.window_rule({
    name  = "windowrule-2",
    match = {
        title = "^(File Operation Progress)$",
        class = "thunar",
    },
    float = true,
})

hl.window_rule({
    name  = "windowrule-3",
    match = {
        title = "^(Rename)(.*)$",
        class = "thunar",
    },
    float = true,
    stay_focused = true,
})

hl.window_rule({
    name  = "windowrule-4",
    match = {
        title = "^(Font Manager)$",
    },
    float = true,
})

hl.window_rule({
    name  = "windowrule-5",
    match = {
        title = "^(DevToolsApp)$",
    },
    float = true,
    size = { 900, 600 },
    move = { "((monitor_w*0.5))", "((monitor_h*0.15))" },
})

hl.window_rule({
    name  = "windowrule-6",
    match = {
        title = "^(Volume Control)$",
    },
    float = true,
    size = { 1100, 500 },
})

hl.window_rule({
    name  = "windowrule-7",
    match = {
        title = "^(Qalculate!)$",
    },
    float = true,
})

hl.window_rule({
    name  = "windowrule-8",
    match = {
        class = "blueman-manager",
    },
    float = true,
})

hl.window_rule({
    name  = "windowrule-9",
    match = {
        class = "blueman-services",
    },
    float = true,
})

hl.window_rule({
    name  = "windowrule-10",
    match = {
        class = "nwg-look",
    },
    float = true,
    size = { 900, 500 },
})

hl.window_rule({
    name  = "windowrule-11",
    match = {
        class = "rog-control-center",
    },
    float = true,
    size = { 1000, 500 },
})

hl.window_rule({
    name  = "windowrule-12",
    match = {
        class = "org.qbittorrent.qBittorrent",
    },
    float = true,
})

hl.window_rule({
    name  = "windowrule-13",
    match = {
        class = "kvantummanager",
    },
    float = true,
})

hl.window_rule({
    name  = "windowrule-14",
    match = {
        class = "xfce-polkit",
    },
    float = true,
    stay_focused = true,
})

hl.window_rule({
    name  = "windowrule-15",
    match = {
        class = "org.polymc.PolyMC",
    },
    float = true,
    size = { 900, 600 },
})

hl.window_rule({
    name  = "windowrule-16",
    match = {
        class = "engrampa",
    },
    float = true,
})

hl.window_rule({
    name  = "windowrule-17",
    match = {
        class = "nm-connection-editor",
    },
    float = true,
})

hl.window_rule({
    name  = "windowrule-18",
    match = {
        class = "spotify",
    },
    float = true,
})

hl.window_rule({
    name  = "windowrule-19",
    match = {
        class = "Notion",
    },
    float = true,
    persistent_size = true,
})

hl.window_rule({
    name  = "windowrule-20",
    match = {
        class = "system-config-printer",
    },
    float = true,
})

hl.window_rule({
    name  = "windowrule-21",
    match = {
        class = "net.lutris.Lutris",
    },
    float = true,
})

hl.window_rule({
    name  = "windowrule-22",
    match = {
        class = "org.bleachbit.BleachBit",
    },
    float = true,
})

hl.window_rule({
    name  = "windowrule-23",
    match = {
        class = "vlc",
    },
    float = true,
})

hl.window_rule({
    name  = "windowrule-24",
    match = {
        class = "exo-desktop-item-edit",
    },
    float = true,
})

hl.window_rule({
    name  = "windowrule-25",
    match = {
        class = "xdg-desktop-portal-gtk",
    },
    float = true,
})

hl.window_rule({
    name  = "windowrule-26",
    match = {
        class = "flameshot",
    },
    float = true,
    no_anim = true,
})

hl.window_rule({
    name  = "windowrule-27",
    match = {
        class = "org.gnome.eog",
    },
    float = true,
})

hl.window_rule({
    name  = "windowrule-28",
    match = {
        class = "qt6ct",
    },
    float = true,
    persistent_size = true,
})

hl.window_rule({
    name  = "windowrule-29",
    match = {
        class = "org.gnome.seahorse.Application",
    },
    float = true,
    size = { 900, 500 },
})

-- Arduino ide file manager menu (native wayland)

hl.window_rule({
    name  = "windowrule-30",
    match = {
        class = "electron",
        title = "(^$)",
    },
    float = true,
})

hl.window_rule({
    name  = "windowrule-31",
    match = {
        class = "electron",
        title = "(Save sketch folder as...)",
    },
    float = true,
})

-- Winetricks

hl.window_rule({
    name  = "windowrule-32",
    match = {
        class = "zenity",
        title = "^(Winetricks -)(.*)",
    },
    float = true,
})

hl.window_rule({
    name  = "windowrule-33",
    match = {
        class = "zenity",
        title = "winetricks",
    },
    float = true,
})

-- Telegram

-- windowrule = fullscreen, class:org.telegram.desktop

hl.window_rule({
    name  = "windowrule-34",
    match = {
        class = "org.telegram.desktop",
        title = "^(Media viewer)",
    },
    float = true,
})

-- Stayfocused

hl.window_rule({
    name  = "windowrule-35",
    match = {
        title = "^(Rename device)$",
        class = "blueman-manager",
    },
    stay_focused = true,
})

hl.window_rule({
    name  = "windowrule-36",
    match = {
        class = "thunar",
    },
    float = true,
})

hl.window_rule({
    name  = "windowrule-37",
    match = {
        title = "^(Create Document from)(.*)$",
        class = "thunar",
    },
    stay_focused = true,
})

hl.window_rule({
    name  = "windowrule-38",
    match = {
        title = "^(New)(.*)(...)$",
        class = "thunar",
    },
    stay_focused = true,
})

hl.window_rule({
    name  = "windowrule-39",
    match = {
        title = "^(Create New Folder)$",
        class = "thunar",
    },
    stay_focused = true,
})

-- windowrule=stayfocused,title:^(Open Workspace from File)$,class:codium

-- windowrule=stayfocused,title:^(Open Folder)$,class:codium

-- windowrule=stayfocused,title:^(Open File)$,class:codium

-- windowrule=stayfocused,title:^(Add Folder to Workspace)$,class:codium

hl.window_rule({
    name  = "windowrule-40",
    match = {
        title = "^(Lutris)$",
        class = "net.lutris.Lutris",
    },
    size = { 1340, 750 },
})

-- Alacritty

hl.window_rule({
    name  = "windowrule-41",
    match = {
        class = "Alacritty",
    },
    opacity = { 0.9, 0.8 },
    border_size = { 2, "override" },
    persistent_size = true,
})

hl.window_rule({
    name  = "windowrule-42",
    match = {
        title = "Picture-in-Picture",
        class = "zen-browser",
    },
    size = { 390, 220 },
    move = { "((monitor_w*0.79))", "((monitor_h*0.06))" },
    float = true,
    no_initial_focus = true,
    pin = true,
})

-- Games

hl.window_rule({
    name  = "windowrule-43",
    match = {
        title = "^(Forza Horizon 4)",
        class = "^(steam_app_)(.*)$",
    },
    fullscreen = true,
})

hl.window_rule({
    name  = "windowrule-44",
    match = {
        title = "^(Geometry Dash)",
        class = "^(steam_app_)(.*)$",
    },
    fullscreen = true,
})

hl.window_rule({
    name  = "windowrule-45",
    match = {
        title = "^(House Flipper 2)",
        class = "^(steam_app_)(.*)$",
    },
    fullscreen = true,
})

-- Tags

hl.window_rule({
    name  = "windowrule-46",
    match = {
        tag = "float",
    },
    float = true,
})

hl.window_rule({
    name  = "windowrule-47",
    match = {
        tag = "opaque",
    },
    opacity = { 1, "override" },
})

hl.window_rule({
    name  = "windowrule-48",
    match = {
        tag = "bordered",
    },
    border_size = { 2, "override" },
})

-- Misc

hl.window_rule({
    name  = "windowrule-49",
    match = {
        class = "io.missioncenter.MissionCenter",
    },
    persistent_size = true,
})

-- Layers

hl.layer_rule({
    match = {
        namespace = "swaync-control-center",
    },
    animation = { "slide", "right" },
})

hl.layer_rule({
    match = {
        namespace = "rofi",
    },
    animation = "slide",
})

hl.layer_rule({
    match = {
        namespace = "swww-daemon",
    },
    no_anim = true,
})

hl.layer_rule({
    match = {
        namespace = "selection",
    },
    no_anim = true,
})
