-- Generated by hyprconf2lua v1.3.2
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- .▄▄ · ▄▄▄ .▄▄▄▄▄▄▄▄▄▄▪   ▐ ▄  ▄▄ • .▄▄ · 

-- ▐█ ▀. ▀▄.▀·•██  •██  ██ •█▌▐█▐█ ▀ ▪▐█ ▀. 

-- ▄▀▀▀█▄▐▀▀▪▄ ▐█.▪ ▐█.▪▐█·▐█▐▐▌▄█ ▀█▄▄▀▀▀█▄

-- ▐█▄▪▐█▐█▄▄▌ ▐█▌· ▐█▌·▐█▌██▐█▌▐█▄▪▐█▐█▄▪▐█

--  ▀▀▀▀  ▀▀▀  ▀▀▀  ▀▀▀ ▀▀▀▀▀ █▪·▀▀▀▀  ▀▀▀▀ 

-- https://wiki.hyprland.org/Configuring/Variables/#sections

hl.config({
    general = {
        gaps_in = 2,
        gaps_out = 5,
        border_size = 0,
        layout = "dwindle",
        snap = {
            enabled = true,
            window_gap = 15,
        },
        col = {
            active_border = "rgb(787c99)",
            inactive_border = "rgba(0a0a0ddb)",
        },
    },
})

hl.config({
    dwindle = {
        pseudotile = true,
        preserve_split = true,
        special_scale_factor = 0.9,
    },
})

hl.config({
    master = {
        special_scale_factor = 0.9,
        new_on_top = true,
        new_status = "master",
    },
})

hl.config({
    decoration = {
        rounding = 15,
        -- dim_inactive = true
        -- dim_strength = 0.2
        blur = {
            enabled = false,
        },
        shadow = {
            enabled = false,
        },
    },
})

hl.config({
    input = {
        follow_mouse = 1,
        sensitivity = -0.2,
        numlock_by_default = true,
        touchpad = {
            natural_scroll = true,
            -- clickfinger_behavior = true
            scroll_factor = 0.2,
        },
        kb_layout = { "us", "ru" },
        kb_options = "grp:alt_shift_toggle",
    },
})

hl.config({
    cursor = {
        hide_on_touch = true,
        inactive_timeout = 10,
        no_hardware_cursors = 0,
    },
})

hl.config({
    misc = {
        disable_autoreload = true,
        force_default_wallpaper = 0,
        disable_hyprland_logo = true,
        animate_manual_resizes = false,
        enable_anr_dialog = false,
        -- disable_hyprland_qtutils_check = true
        focus_on_activate = true,
        vrr = 1,
        vfr = true,
    },
})

hl.config({
    xwayland = {
        enabled = true,
        force_zero_scaling = true,
    },
})

hl.config({
    binds = {
        workspace_back_and_forth = true,
        movefocus_cycles_fullscreen = true,
    },
})

hl.config({
    render = {
        direct_scanout = 0,
    },
})

hl.config({
    ecosystem = {
        no_update_news = true,
        no_donation_nag = true,
    },
})

hl.config({
    gestures = {
        workspace_swipe_distance = 1000,
        workspace_swipe_min_speed_to_force = 30,
        workspace_swipe_direction_lock = false,
        workspace_swipe_cancel_ratio = 0.1,
    },
})

hl.workspace_rule({ workspace = 1, persistent = true })
hl.workspace_rule({ workspace = 2, persistent = true })
hl.workspace_rule({ workspace = 3, persistent = true })
hl.workspace_rule({ workspace = 4, persistent = true })
hl.workspace_rule({ workspace = 5, persistent = true })
hl.workspace_rule({ workspace = 6, persistent = true })

hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })
hl.gesture({ fingers = 4, direction = "pinch", action = "fullscreen" })
