---@module 'hl'

-- Auto-generated by DMS - do not edit manually
-- Remove require("dms.colors") from your config to override.

hl.config({
    general = {
        col = {
            active_border = "rgb(5dc7cf)",
            inactive_border = "rgb(ff00ff)",
        },
    },
})

hl.config({
    group = {
        col = {
            border_active = "rgb(5dc7cf)",
            border_inactive = "rgb(ff00ff)",
            border_locked_active = "rgb(ff4080)",
            border_locked_inactive = "rgb(ff00ff)",
        },
        groupbar = {
            col = {
                active = "rgb(5dc7cf)",
                inactive = "rgb(ff00ff)",
                locked_active = "rgb(ff4080)",
                locked_inactive = "rgb(ff00ff)",
            },
        },
    },
})
