-- Generated by hyprconf2lua v1.3.2
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Auto-generated by DMS - do not edit manually

hl.env("HYPRCURSOR_THEME", "Adwaita")

hl.env("XCURSOR_THEME", "Adwaita")

hl.env("HYPRCURSOR_SIZE", 27)

hl.env("XCURSOR_SIZE", 27)
