-- Generated by hyprconf2lua v1.3.2
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Auto-generated by DMS - do not edit manually

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "1920x1080@60.000",
    position = "0x0",
    scale    = 1,
    transform = 1,
    vrr = 0,
})

hl.monitor({
    output   = "DP-2",
    mode     = "2560x1440@59.951",
    position = "1108x488",
    scale    = 1,
    vrr = 0,
})
